### ISSUE TITLE
Create initial release and test with Ruter EMQX Lambdas

### ISSUE THREAD

**Issue by edwdev** [basefarm/mqtt-py-wrapper#1]
## Implement via semi TDD

- [x] Client connect
- [x] Message publish
- [x] Message receive
- [x] Retain create
- [x] Retain delete
- [x] MQTT and WebSocket
- [x] TCP and TLS
- [x] Mqtt version 3.1.0
- [x] Mqtt version 3.1.1
- [x] Mqtt version 5.0.0
- [x] Authentication with username / pass
- [ ] Implement logic for marking when reinitialization of client is needed
- [ ] Implement logic for marking when reconnection of client is needed

## Documentation
- [ ] Library goal
- [ ] Short class explanations
- [ ] Example uses

**Comment by thomasfinstad** [comment]
Able to connect and verify a sent and received message

**Comment by thomasfinstad** [comment]
718b350 Initial TLS class added as broken code to act as a _note_ that TLS needs to be figured out, also have parametrized testing to ease coverage of all the needed functions.

**Comment by thomasfinstad** [comment]
61c648f Protocols and transports working.

**Comment by thomasfinstad** [comment]
8ecbc0e Auth is now working with username / password and used during testing

**Comment by thomasfinstad** [comment]
Abandon
